name: "Sync Medium RSS"
on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-repo-portfolio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npx tsc

      - name: Run Medium RSS Fetcher
        env:
          FEED_URL: "https://medium.com/feed/@mariaadriana15"
        run: node dist/index.js
        
      - name: Clone Personal Portfolio Repo
        run: |
          git clone https://github.com/mariadriana-deemaze/portfolio-2024 repo-portfolio
          cd repo-portfolio
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"

      - name: Copy Generated Files to Personal Portfolio Repo
        run: |
          if [ "$(ls -A _output 2>/dev/null)" ]; then
            echo "Found new medium posts. Copying files..."
            cp -r _output/* repo-portfolio/data/blog  # Copy all generated markdown files
            cd repo-portfolio
            git add .
            git commit -m $'scheduled 🤖 : Update Medium articles\n\nCo-authored-by: mariadriana-deemaze <maria.adriana.cardoso@deemaze.com>' || echo "No changes to commit"
            git push https://mariadriana-deemaze:${{ secrets.TARGET_REPO_PAT }}@github.com/mariadriana-deemaze/portfolio-2024.git main
          else
            echo "No new medium posts found. Exiting gracefully."
          fi
          